name: Turrets
version: 1.0
main: com.gmail.czahrien.Turrets.Turrets
commands:
  turret:
    description: Sets various properties of a placable turret.
    usage: /turret [speed|firerate|type|los|distance|save] [remaining args]
    permission: Turrets.edit
permissions:
  Turrets.*:
    description: Allows editing of turrets and turrets will ignore the placer.
    children:
      Turrets.edit: true
      Turrets.ignore: true
  Turrets.edit:
    description: Allows editing of turrets.
    default: op
  Turrets.ignore:
    description: Turrets ignore players with this node.
    default: false